In [1]:
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
import os
os.chdir("/content/drive/MyDrive/[06] Learning and Teaching/Transit_Folder/IP/Oct'25/LDA/New")

In [4]:
!ls

LDA_New.ipynb  nba_final.csv

In [5]:
data = pd.read_csv('nba_final.csv')

In [6]:
data.head()

,Rk,Player.x,Player_ID,Pos1,Pos2,Age,Tm,G,GS,MP,...,Conference,Role,Fvot,FRank,Pvot,PRank,Mvot,MRank,Score,Play
0,170,A.J. Hammons,hammoaj01,C,NaN,24,DAL,22,0,7.4,...,West,Front,786,123,NaN,NaN,NaN,NaN,83.5,No
1,58,Aaron Brooks,brookaa01,PG,NaN,32,IND,65,0,13.8,...,Est,Back,2474,64,NaN,NaN,NaN,NaN,48.2,No
2,157,Aaron Gordon,gordoaa01,SF,NaN,21,ORL,80,72,28.7,...,Est,Front,22774,29,NaN,NaN,NaN,NaN,40.0,No
3,352,Adreian Payne,paynead01,PF,NaN,25,MIN,18,0,7.5,...,West,Front,861,120,1.0,52.0,NaN,NaN,75.5,No
4,10,Al-Farouq Aminu,aminual01,PF,NaN,26,POR,61,25,29.1,...,West,Front,4971,69,7.0,23.0,NaN,NaN,42.8,No

In [7]:
data.shape

(1408, 45)

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1408 entries, 0 to 1407
Data columns (total 45 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Rk          1408 non-null   int64
 1   Player.x    1408 non-null   object
 2   Player_ID   1408 non-null   object
 3   Pos1        1408 non-null   object
 4   Pos2        12 non-null     object
 5   Age         1408 non-null   int64
 6   Tm          1408 non-null   object
 7   G           1408 non-null   int64
 8   GS          1408 non-null   int64
 9   MP          1408 non-null   float64
 10  FG          1408 non-null   float64
 11  FGA         1408 non-null   float64
 12  FG.         1404 non-null   float64
 13  X3P         1408 non-null   float64
 14  X3PA        1408 non-null   float64
 15  X3P.        1309 non-null   float64
 16  X2P         1408 non-null   float64
 17  X2PA        1408 non-null   float64
 18  X2P.        1393 non-null   float64
 19  eFG.        1404 non-null   float64
 20  FT          1408 non-null   float64
 21  FTA         1408 non-null   float64
 22  FT.         1361 non-null   float64
 23  ORB         1408 non-null   float64
 24  DRB         1408 non-null   float64
 25  TRB         1408 non-null   float64
 26  AST         1408 non-null   float64
 27  STL         1408 non-null   float64
 28  BLK         1408 non-null   float64
 29  TOV         1408 non-null   float64
 30  PF          1408 non-null   float64
 31  PTS         1408 non-null   float64
 32  Salary      1346 non-null   float64
 33  mean_views  1270 non-null   float64
 34  Season      1408 non-null   object
 35  Conference  1408 non-null   object
 36  Role        1408 non-null   object
 37  Fvot        1408 non-null   int64
 38  FRank       1408 non-null   int64
 39  Pvot        1249 non-null   float64
 40  PRank       1249 non-null   float64
 41  Mvot        1004 non-null   float64
 42  MRank       1004 non-null   float64
 43  Score       1408 non-null   float64
 44  Play        1408 non-null   object
dtypes: float64(30), int64(6), object(9)
memory usage: 495.1+ KB

In [9]:
data.columns

Index(['Rk', 'Player.x', 'Player_ID', 'Pos1', 'Pos2', 'Age', 'Tm', 'G', 'GS',
       'MP', 'FG', 'FGA', 'FG.', 'X3P', 'X3PA', 'X3P.', 'X2P', 'X2PA', 'X2P.',
       'eFG.', 'FT', 'FTA', 'FT.', 'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK',
       'TOV', 'PF', 'PTS', 'Salary', 'mean_views', 'Season', 'Conference',
       'Role', 'Fvot', 'FRank', 'Pvot', 'PRank', 'Mvot', 'MRank', 'Score',
       'Play'],
      dtype='object')

In [15]:
for each in data.columns:
  if data[each].nunique() <= 10:
    print(each, data[each].nunique())

Pos1 5
Pos2 4
Season 3
Conference 2
Role 2
MRank 9
Play 2

In [16]:
data['MRank']

0       NaN
1       NaN
2       NaN
3       NaN
4       NaN
       ...
1403    8.0
1404    8.0
1405    8.0
1406    7.0
1407    8.0
Name: MRank, Length: 1408, dtype: float64

In [18]:
data.isna().sum()

Rk               0
Player.x         0
Player_ID        0
Pos1             0
Pos2          1396
Age              0
Tm               0
G                0
GS               0
MP               0
FG               0
FGA              0
FG.              4
X3P              0
X3PA             0
X3P.            99
X2P              0
X2PA             0
X2P.            15
eFG.             4
FT               0
FTA              0
FT.             47
ORB              0
DRB              0
TRB              0
AST              0
STL              0
BLK              0
TOV              0
PF               0
PTS              0
Salary          62
mean_views     138
Season           0
Conference       0
Role             0
Fvot             0
FRank            0
Pvot           159
PRank          159
Mvot           404
MRank          404
Score            0
Play             0
dtype: int64

In [19]:
import numpy as np
data['Pos2'] = data['Pos2'].replace(np.nan, 'NONE')
data['Pos2'].unique()

array(['NONE', 'C', 'SG', 'SF', 'PF'], dtype=object)

In [20]:
data = data.fillna(0)

In [22]:
data.isna().sum()

Rk            0
Player.x      0
Player_ID     0
Pos1          0
Pos2          0
Age           0
Tm            0
G             0
GS            0
MP            0
FG            0
FGA           0
FG.           0
X3P           0
X3PA          0
X3P.          0
X2P           0
X2PA          0
X2P.          0
eFG.          0
FT            0
FTA           0
FT.           0
ORB           0
DRB           0
TRB           0
AST           0
STL           0
BLK           0
TOV           0
PF            0
PTS           0
Salary        0
mean_views    0
Season        0
Conference    0
Role          0
Fvot          0
FRank         0
Pvot          0
PRank         0
Mvot          0
MRank         0
Score         0
Play          0
dtype: int64

In [ ]:
data.head()

,Rk,Player.x,Player_ID,Pos1,Pos2,Age,Tm,G,GS,MP,...,Conference,Role,Fvot,FRank,Pvot,PRank,Mvot,MRank,Score,Play
0,170,A.J. Hammons,hammoaj01,C,NONE,24,DAL,22,0,7.4,...,West,Front,786,123,0.0,0.0,0.0,0.0,83.5,No
1,58,Aaron Brooks,brookaa01,PG,NONE,32,IND,65,0,13.8,...,Est,Back,2474,64,0.0,0.0,0.0,0.0,48.2,No
2,157,Aaron Gordon,gordoaa01,SF,NONE,21,ORL,80,72,28.7,...,Est,Front,22774,29,0.0,0.0,0.0,0.0,40.0,No
3,352,Adreian Payne,paynead01,PF,NONE,25,MIN,18,0,7.5,...,West,Front,861,120,1.0,52.0,0.0,0.0,75.5,No
4,10,Al-Farouq Aminu,aminual01,PF,NONE,26,POR,61,25,29.1,...,West,Front,4971,69,7.0,23.0,0.0,0.0,42.8,No

In [23]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1408 entries, 0 to 1407
Data columns (total 45 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Rk          1408 non-null   int64
 1   Player.x    1408 non-null   object
 2   Player_ID   1408 non-null   object
 3   Pos1        1408 non-null   object
 4   Pos2        1408 non-null   object
 5   Age         1408 non-null   int64
 6   Tm          1408 non-null   object
 7   G           1408 non-null   int64
 8   GS          1408 non-null   int64
 9   MP          1408 non-null   float64
 10  FG          1408 non-null   float64
 11  FGA         1408 non-null   float64
 12  FG.         1408 non-null   float64
 13  X3P         1408 non-null   float64
 14  X3PA        1408 non-null   float64
 15  X3P.        1408 non-null   float64
 16  X2P         1408 non-null   float64
 17  X2PA        1408 non-null   float64
 18  X2P.        1408 non-null   float64
 19  eFG.        1408 non-null   float64
 20  FT          1408 non-null   float64
 21  FTA         1408 non-null   float64
 22  FT.         1408 non-null   float64
 23  ORB         1408 non-null   float64
 24  DRB         1408 non-null   float64
 25  TRB         1408 non-null   float64
 26  AST         1408 non-null   float64
 27  STL         1408 non-null   float64
 28  BLK         1408 non-null   float64
 29  TOV         1408 non-null   float64
 30  PF          1408 non-null   float64
 31  PTS         1408 non-null   float64
 32  Salary      1408 non-null   float64
 33  mean_views  1408 non-null   float64
 34  Season      1408 non-null   object
 35  Conference  1408 non-null   object
 36  Role        1408 non-null   object
 37  Fvot        1408 non-null   int64
 38  FRank       1408 non-null   int64
 39  Pvot        1408 non-null   float64
 40  PRank       1408 non-null   float64
 41  Mvot        1408 non-null   float64
 42  MRank       1408 non-null   float64
 43  Score       1408 non-null   float64
 44  Play        1408 non-null   object
dtypes: float64(30), int64(6), object(9)
memory usage: 495.1+ KB

In [24]:
data = data.drop(['Player.x','Player_ID'], axis=1)

In [27]:
data.groupby(data['Play']).mean()

TypeError: agg function failed [how->mean,dtype->object]

In [28]:
data.groupby(data['Play']).mean(numeric_only=True)

,Rk,Age,G,GS,MP,FG,FGA,FG.,X3P,X3PA,...,PTS,Salary,mean_views,Fvot,FRank,Pvot,PRank,Mvot,MRank,Score
Play,,,,,,,,,,,,,,,,,,,,,
No,258.435955,26.059925,53.027715,23.379026,19.413184,2.996030,6.631461,0.444646,0.792884,2.256105,...,8.016854,5.710804e+06,662.445828,5.296657e+04,64.638202,2.860674,40.202247,0.087640,5.171536,79.163146
Yes,244.273973,27.589041,73.698630,72.136986,33.869863,8.134247,17.079452,0.477151,2.015068,5.432877,...,23.009589,2.076003e+07,5087.858807,1.301453e+06,5.945205,86.876712,5.164384,38.808219,3.753425,10.020548

In [29]:
data.describe().T

,count,mean,std,min,25%,50%,75%,max
Rk,1408.0,2.577017e+02,1.507659e+02,1.0,1.270000e+02,2.570000e+02,3.852500e+02,5.400000e+02
Age,1408.0,2.613920e+01,4.282550e+00,19.0,2.300000e+01,2.500000e+01,2.900000e+01,4.200000e+01
G,1408.0,5.409943e+01,2.405251e+01,1.0,3.600000e+01,6.200000e+01,7.400000e+01,8.200000e+01
GS,1408.0,2.590696e+01,2.866458e+01,0.0,1.000000e+00,1.300000e+01,5.200000e+01,8.200000e+01
MP,1408.0,2.016271e+01,9.066041e+00,0.7,1.330000e+01,2.000000e+01,2.750000e+01,3.780000e+01
FG,1408.0,3.262429e+00,2.181694e+00,0.0,1.600000e+00,2.800000e+00,4.500000e+00,1.080000e+01
FGA,1408.0,7.173153e+00,4.591826e+00,0.0,3.700000e+00,6.150000e+00,9.900000e+00,2.450000e+01
FG.,1408.0,4.463317e-01,9.467931e-02,0.0,4.030000e-01,4.430000e-01,4.900000e-01,1.000000e+00
X3P,1408.0,8.562500e-01,7.923071e-01,0.0,2.000000e-01,7.000000e-01,1.300000e+00,5.100000e+00
X3PA,1408.0,2.420810e+00,2.061737e+00,0.0,7.000000e-01,2.050000e+00,3.700000e+00,1.320000e+01
X3P.,1408.0,2.905362e-01,1.463607e-01,0.0,2.560000e-01,3.330000e-01,3.720000e-01,1.000000e+00
X2P,1408.0,2.406321e+00,1.812374e+00,0.0,1.000000e+00,1.900000e+00,3.300000e+00,9.700000e+00
X2PA,1408.0,4.752770e+00,3.427045e+00,0.0,2.100000e+00,3.800000e+00,6.700000e+00,1.920000e+01
X2P.,1408.0,4.914077e-01,1.064323e-01,0.0,4.520000e-01,4.970000e-01,5.440000e-01,1.000000e+00
eFG.,1408.0,5.039517e-01,9.839753e-02,0.0,4.730000e-01,5.100000e-01,5.490000e-01,1.500000e+00
FT,1408.0,1.417401e+00,1.369218e+00,0.0,5.000000e-01,1.000000e+00,1.900000e+00,9.700000e+00
FTA,1408.0,1.855327e+00,1.678879e+00,0.0,7.000000e-01,1.300000e+00,2.500000e+00,1.100000e+01
FT.,1408.0,7.161044e-01,1.842538e-01,0.0,6.670000e-01,7.600000e-01,8.240000e-01,1.000000e+00
ORB,1408.0,8.475142e-01,7.697050e-01,0.0,3.000000e-01,6.000000e-01,1.100000e+00,5.400000e+00
DRB,1408.0,2.824645e+00,1.853155e+00,0.0,1.500000e+00,2.400000e+00,3.700000e+00,1.110000e+01
TRB,1408.0,3.670170e+00,2.482460e+00,0.0,1.900000e+00,3.100000e+00,4.700000e+00,1.600000e+01
AST,1408.0,1.935227e+00,1.791822e+00,0.0,7.000000e-01,1.300000e+00,2.500000e+00,1.120000e+01
STL,1408.0,6.407670e-01,4.160258e-01,0.0,3.000000e-01,6.000000e-01,9.000000e-01,2.400000e+00
BLK,1408.0,4.026989e-01,4.036875e-01,0.0,1.000000e-01,3.000000e-01,5.000000e-01,2.700000e+00
TOV,1408.0,1.130540e+00,8.032480e-01,0.0,6.000000e-01,9.000000e-01,1.500000e+00,5.700000e+00
PF,1408.0,1.726065e+00,7.517208e-01,0.0,1.200000e+00,1.700000e+00,2.200000e+00,4.000000e+00
PTS,1408.0,8.794176e+00,6.081955e+00,0.0,4.300000e+00,7.300000e+00,1.200000e+01,3.610000e+01
Salary,1408.0,6.491055e+06,7.418582e+06,0.0,1.349936e+06,3.127094e+06,9.904495e+06,3.745715e+07
mean_views,1408.0,8.918884e+02,2.045319e+03,0.0,1.274774e+02,3.609945e+02,8.489027e+02,3.414796e+04
Fvot,1408.0,1.176963e+05,4.286272e+05,3.0,2.135500e+03,6.843000e+03,2.925250e+04,4.620809e+06
FRank,1408.0,6.159517e+01,3.668110e+01,1.0,3.000000e+01,6.000000e+01,9.025000e+01,1.450000e+02
Pvot,1408.0,7.216619e+00,2.502276e+01,0.0,0.000000e+00,1.000000e+00,3.000000e+00,2.690000e+02
PRank,1408.0,3.838565e+01,2.600508e+01,0.0,1.600000e+01,3.900000e+01,6.000000e+01,8.800000e+01
Mvot,1408.0,2.095170e+00,1.260784e+01,0.0,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+02
MRank,1408.0,5.098011e+00,3.473575e+00,0.0,0.000000e+00,7.000000e+00,8.000000e+00,9.000000e+00
Score,1408.0,7.557834e+01,4.140498e+01,1.0,4.500000e+01,6.990000e+01,1.092000e+02,1.668000e+02

In [30]:
from sklearn.preprocessing import LabelEncoder

Le = LabelEncoder()

data['Pos1'] = Le.fit_transform(data['Pos1'])
data['Pos2'] = Le.fit_transform(data['Pos2'])
data['Tm'] = Le.fit_transform(data['Tm'])
data['Season'] = Le.fit_transform(data['Season'])
data['Conference'] = Le.fit_transform(data['Conference'])
data['Role'] = Le.fit_transform(data['Role'])
data['Play'] = Le.fit_transform(data['Play'])

## Method 1

In [33]:
feature_variables= ['Rk', 'Pos1', 'Pos2', 'Age', 'Tm', 'G', 'GS', 'MP', 'FG', 'FGA', 'FG.',
       'X3P', 'X3PA', 'X3P.', 'X2P', 'X2PA', 'X2P.', 'eFG.', 'FT', 'FTA',
       'FT.', 'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS',
       'Salary', 'mean_views', 'Season', 'Conference', 'Role', 'Fvot', 'FRank',
       'Pvot', 'PRank', 'Mvot', 'MRank', 'Score']
target_variable = ['Play']

In [ ]:
X1 = data[feature_variables]
y1 = data[target_variable]

## Method 2

In [31]:
X = data.drop(['Play'], axis=1)
y = data['Play']

In [34]:
#standardize
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X = sc.fit_transform(X)

In [35]:
X.shape

(1408, 42)

In [36]:
data['Play'].unique()

array([0, 1])

In [38]:
#LDA
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
lda = LinearDiscriminantAnalysis(n_components=1)
X = lda.fit_transform(X, y)

In [39]:
X.shape

(1408, 1)

In [40]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.3, random_state=29)

In [ ]:
# Initiate the Model
# Train the Model
# Evaluate the Model

In [46]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report

logit = LogisticRegression()
dt = DecisionTreeClassifier()
rf = RandomForestClassifier()

logit.fit(X_train, y_train)

LogisticRegression()

In [47]:
logit.score(X_train, y_train)

0.9756345177664975

In [48]:
def train_model(model, X_train, X_test, y_train, y_test):
  model.fit(X_train, y_train)
  print("Training", model.score(X_train, y_train))
  print("Testing", model.score(X_test, y_test))

In [51]:
model = rf
train_model(model, X_train, X_test, y_train, y_test)

Training 1.0
Testing 0.9645390070921985

In [53]:
listOfModel = [logit, dt, rf]
for each in listOfModel:
  train_model(each, X_train, X_test, y_train, y_test)

Training 0.9756345177664975
Testing 0.983451536643026
Training 1.0
Testing 0.9645390070921985
Training 1.0
Testing 0.9645390070921985

In [41]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression()

In [42]:
lr.fit(X_train, y_train)

LogisticRegression()

In [43]:
lr_pred = lr.predict(X_test)

In [44]:
from sklearn.metrics import classification_report

cr = classification_report(lr_pred, y_test)
print(cr)

              precision    recall  f1-score   support

           0       1.00      0.99      0.99       409
           1       0.68      0.93      0.79        14

    accuracy                           0.98       423
   macro avg       0.84      0.96      0.89       423
weighted avg       0.99      0.98      0.98       423

In [ ]:
from sklearn.tree import DecisionTreeClassifier

dt = DecisionTreeClassifier()

In [ ]:
dt.fit(X_train, y_train)

DecisionTreeClassifier()

In [ ]:
pred_dt = dt.predict(X_test)

In [ ]:
cr_dt = classification_report(pred_dt, y_test)
print(cr_dt)

              precision    recall  f1-score   support

           0       0.98      0.99      0.98       401
           1       0.68      0.59      0.63        22

    accuracy                           0.96       423
   macro avg       0.83      0.79      0.81       423
weighted avg       0.96      0.96      0.96       423

In [ ]:
#random forest classifier
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier()

In [ ]:
rf.fit(X_train, y_train)

RandomForestClassifier()

In [ ]:
pred_rf = rf.predict(X_test)

In [ ]:
cr_rf = classification_report(pred_rf, y_test)
print(cr_rf)

              precision    recall  f1-score   support

           0       0.98      0.99      0.98       401
           1       0.68      0.59      0.63        22

    accuracy                           0.96       423
   macro avg       0.83      0.79      0.81       423
weighted avg       0.96      0.96      0.96       423

# Using LDA for Classification

In [54]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.3, random_state=29)

In [55]:
lda = LinearDiscriminantAnalysis(n_components=1)

In [56]:
lda.fit(X_train, y_train)

LinearDiscriminantAnalysis(n_components=1)

In [57]:
lda.predict(X_test)

array([0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0])