In [ ]:
import numpy as np
import pandas as pd


df = pd.read_csv('housing.csv')
df

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,20141013T000000,221900,3,1.00,1180,5650,1.0,0,0,...,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,6414100192,20141209T000000,538000,3,2.25,2570,7242,2.0,0,0,...,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,5631500400,20150225T000000,180000,2,1.00,770,10000,1.0,0,0,...,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,2487200875,20141209T000000,604000,4,3.00,1960,5000,1.0,0,0,...,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,1954400510,20150218T000000,510000,3,2.00,1680,8080,1.0,0,0,...,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21608,263000018,20140521T000000,360000,3,2.50,1530,1131,3.0,0,0,...,8,1530,0,2009,0,98103,47.6993,-122.346,1530,1509
21609,6600060120,20150223T000000,400000,4,2.50,2310,5813,2.0,0,0,...,8,2310,0,2014,0,98146,47.5107,-122.362,1830,7200
21610,1523300141,20140623T000000,402101,2,0.75,1020,1350,2.0,0,0,...,7,1020,0,2009,0,98144,47.5944,-122.299,1020,2007
21611,291310100,20150116T000000,400000,3,2.50,1600,2388,2.0,0,0,...,8,1600,0,2004,0,98027,47.5345,-122.069,1410,1287
21612,1523300157,20141015T000000,325000,2,0.75,1020,1076,2.0,0,0,...,7,1020,0,2008,0,98144,47.5941,-122.299,1020,1357

In [ ]:
df.loc[0:, 'waterfront'].sum()

163

In [ ]:
filter_1 = df.loc[0:,'price'].max()
filter_2 = df['price'].max()
filter_3 = df['price']== filter_2
print(filter_1)
print(filter_2)
print(filter_3)
df[filter_3]

7700000
7700000
0        False
1        False
2        False
3        False
4        False
         ...
21608    False
21609    False
21610    False
21611    False
21612    False
Name: price, Length: 21613, dtype: bool

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
7252,6762700020,20141013T000000,7700000,6,8.0,12050,27600,2.5,0,3,...,13,8570,3480,1910,1987,98102,47.6298,-122.323,3940,8800

In [ ]:
countOfgrade = (df['grade']== 10)
df[countOfgrade].count()

id               1134
date             1134
price            1134
bedrooms         1134
bathrooms        1134
sqft_living      1134
sqft_lot         1134
floors           1134
waterfront       1134
view             1134
condition        1134
grade            1134
sqft_above       1134
sqft_basement    1134
yr_built         1134
yr_renovated     1134
zipcode          1134
lat              1134
long             1134
sqft_living15    1134
sqft_lot15       1134
dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21613 entries, 0 to 21612
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             21613 non-null  int64
 1   date           21613 non-null  object
 2   price          21613 non-null  int64
 3   bedrooms       21613 non-null  int64
 4   bathrooms      21613 non-null  float64
 5   sqft_living    21613 non-null  int64
 6   sqft_lot       21613 non-null  int64
 7   floors         21613 non-null  float64
 8   waterfront     21613 non-null  int64
 9   view           21613 non-null  int64
 10  condition      21613 non-null  int64
 11  grade          21613 non-null  int64
 12  sqft_above     21613 non-null  int64
 13  sqft_basement  21613 non-null  int64
 14  yr_built       21613 non-null  int64
 15  yr_renovated   21613 non-null  int64
 16  zipcode        21613 non-null  int64
 17  lat            21613 non-null  float64
 18  long           21613 non-null  float64
 19  sqft_living15  21613 non-null  int64
 20  sqft_lot15     21613 non-null  int64
dtypes: float64(4), int64(16), object(1)
memory usage: 3.5+ MB

In [ ]:
cust_id_filter = df['id']==9126100861
df[cust_id_filter]

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
400,9126100861,20150306T000000,557000,3,3.5,1710,2096,2.0,0,0,...,8,1290,420,2008,0,98122,47.6055,-122.305,1630,1543

In [ ]:
view_filter = df['view']==3
df[view_filter]

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
15,9297300055,20150124T000000,650000,4,3.00,2950,5000,2.0,0,3,...,9,1980,970,1979,0,98126,47.5714,-122.375,2140,4000
60,1516000055,20141210T000000,650000,3,2.25,2150,21235,1.0,0,3,...,8,1590,560,1959,0,98166,47.4336,-122.339,2570,18900
114,8961960160,20141028T000000,480000,4,2.50,3230,16171,2.0,0,3,...,9,2520,710,2001,0,98001,47.3183,-122.253,2640,8517
153,7855801670,20150401T000000,2250000,4,3.25,5180,19850,2.0,0,3,...,12,3540,1640,2006,0,98006,47.5620,-122.162,3160,9750
216,46100204,20150221T000000,1505000,5,3.00,3300,33474,1.0,0,3,...,9,1870,1430,1957,1991,98040,47.5673,-122.210,3836,20953
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21327,7394400080,20150304T000000,535000,4,3.25,2840,4000,2.0,0,3,...,9,2330,510,2014,0,98108,47.5529,-122.293,2160,4867
21344,8835770170,20140822T000000,1488000,5,6.00,6880,279968,2.0,0,3,...,12,4070,2810,2007,0,98045,47.4624,-121.779,4690,256803
21505,9468200109,20140617T000000,1555000,3,3.50,4360,6240,2.0,0,3,...,10,2960,1400,2008,0,98103,47.6791,-122.354,1920,3910
21539,8902000201,20150219T000000,338500,3,2.25,1333,1470,3.0,0,3,...,7,1333,0,2009,0,98125,47.7058,-122.302,1360,1680
21540,715010530,20150113T000000,1881583,5,3.50,4410,13000,2.0,0,3,...,10,2920,1490,2014,0,98006,47.5382,-122.111,5790,12969

In [ ]:
filter_min_price = df['price'].min()
print(filter_min_price)
df[(df['price']==filter_min_price)]

75000

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
1149,3421079032,20150217T000000,75000,1,0.0,670,43377,1.0,0,0,...,3,670,0,1966,0,98022,47.2638,-121.906,1160,42882

In [ ]:
df.head()

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,20141013T000000,221900,3,1.00,1180,5650,1.0,0,0,...,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,6414100192,20141209T000000,538000,3,2.25,2570,7242,2.0,0,0,...,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,5631500400,20150225T000000,180000,2,1.00,770,10000,1.0,0,0,...,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,2487200875,20141209T000000,604000,4,3.00,1960,5000,1.0,0,0,...,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,1954400510,20150218T000000,510000,3,2.00,1680,8080,1.0,0,0,...,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503

In [ ]:
df[df['sqft_living']==(df['sqft_living'].max())]

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
12777,1225069038,20140505T000000,2280000,7,8.0,13540,307752,3.0,0,4,...,12,9410,4130,1999,0,98053,47.6675,-121.986,4850,217800

In [ ]:
pd_series = pd.Series([1,2,3,4.0, 'str'])
np.ndim(df)
np.ndim(pd_series)
pd_series

0      1
1      2
2      3
3    4.0
4    str
dtype: object

In [ ]:
filter_1 = (df['sqft_lot'] > 0) & (df['sqft_above'] < 400)
df_new = df[filter_1]
df_new

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
860,1723049033,20140620T000000,245000,1,0.75,380,15000,1.0,0,0,...,5,380,0,1963,0,98168,47.4810,-122.323,1170,15000
4868,6896300380,20141002T000000,228000,0,1.00,390,5900,1.0,0,0,...,4,390,0,1953,0,98118,47.5260,-122.261,2170,6000
15381,2856101479,20140701T000000,276000,1,0.75,370,1801,1.0,0,0,...,5,370,0,1923,0,98117,47.6778,-122.389,1340,5000
18379,1222029077,20141029T000000,265000,0,0.75,384,213444,1.0,0,0,...,4,384,0,2003,0,98070,47.4177,-122.491,1920,224341
19452,3980300371,20140926T000000,142000,0,0.00,290,20875,1.0,0,0,...,1,290,0,1963,0,98024,47.5308,-121.888,1620,22850
21332,9266700190,20150511T000000,245000,1,1.00,390,2000,1.0,0,0,...,6,390,0,1920,0,98103,47.6938,-122.347,1340,5100

In [ ]:
for index, row in df_new.iterrows() :
  print(f"date: {df_new['date']} , view: {df_new['view']}, city: {df_new['grade']} ")
  print()

# def increase_grade(house_index):
#   df['sqft_lot' > 0 & 'sqft_lot' < 400]

date: 860      20140620T000000
4868     20141002T000000
15381    20140701T000000
18379    20141029T000000
19452    20140926T000000
21332    20150511T000000
Name: date, dtype: object , view: 860      0
4868     0
15381    0
18379    0
19452    0
21332    0
Name: view, dtype: int64, city: 860      5
4868     4
15381    5
18379    4
19452    1
21332    6
Name: grade, dtype: int64

date: 860      20140620T000000
4868     20141002T000000
15381    20140701T000000
18379    20141029T000000
19452    20140926T000000
21332    20150511T000000
Name: date, dtype: object , view: 860      0
4868     0
15381    0
18379    0
19452    0
21332    0
Name: view, dtype: int64, city: 860      5
4868     4
15381    5
18379    4
19452    1
21332    6
Name: grade, dtype: int64

date: 860      20140620T000000
4868     20141002T000000
15381    20140701T000000
18379    20141029T000000
19452    20140926T000000
21332    20150511T000000
Name: date, dtype: object , view: 860      0
4868     0
15381    0
18379    0
19452    0
21332    0
Name: view, dtype: int64, city: 860      5
4868     4
15381    5
18379    4
19452    1
21332    6
Name: grade, dtype: int64

date: 860      20140620T000000
4868     20141002T000000
15381    20140701T000000
18379    20141029T000000
19452    20140926T000000
21332    20150511T000000
Name: date, dtype: object , view: 860      0
4868     0
15381    0
18379    0
19452    0
21332    0
Name: view, dtype: int64, city: 860      5
4868     4
15381    5
18379    4
19452    1
21332    6
Name: grade, dtype: int64

date: 860      20140620T000000
4868     20141002T000000
15381    20140701T000000
18379    20141029T000000
19452    20140926T000000
21332    20150511T000000
Name: date, dtype: object , view: 860      0
4868     0
15381    0
18379    0
19452    0
21332    0
Name: view, dtype: int64, city: 860      5
4868     4
15381    5
18379    4
19452    1
21332    6
Name: grade, dtype: int64

date: 860      20140620T000000
4868     20141002T000000
15381    20140701T000000
18379    20141029T000000
19452    20140926T000000
21332    20150511T000000
Name: date, dtype: object , view: 860      0
4868     0
15381    0
18379    0
19452    0
21332    0
Name: view, dtype: int64, city: 860      5
4868     4
15381    5
18379    4
19452    1
21332    6
Name: grade, dtype: int64

In [ ]:
df[df.duplicated(['id','zipcode','grade'])]

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
94,6021501535,20141223T000000,700000,3,1.50,1580,5000,1.0,0,0,...,8,1290,290,1939,0,98117,47.6870,-122.386,1570,4500
314,4139480200,20141209T000000,1400000,4,3.25,4290,12103,1.0,0,3,...,11,2690,1600,1997,0,98006,47.5503,-122.102,3860,11244
325,7520000520,20150311T000000,240500,2,1.00,1240,12092,1.0,0,0,...,6,960,280,1922,1984,98146,47.4957,-122.352,1820,7460
346,3969300030,20141229T000000,239900,4,1.00,1000,7134,1.0,0,0,...,6,1000,0,1943,0,98178,47.4897,-122.240,1020,7138
372,2231500030,20150324T000000,530000,4,2.25,2180,10754,1.0,0,0,...,7,1100,1080,1954,0,98133,47.7711,-122.341,1810,6929
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20181,7853400250,20150219T000000,645000,4,3.50,2910,5260,2.0,0,0,...,9,2910,0,2012,0,98065,47.5168,-121.883,2910,5260
20613,2724049222,20141201T000000,220000,2,2.50,1000,1092,2.0,0,0,...,7,990,10,2004,0,98118,47.5419,-122.271,1330,1466
20670,8564860270,20150330T000000,502000,4,2.50,2680,5539,2.0,0,0,...,8,2680,0,2013,0,98045,47.4759,-121.734,2680,5992
20780,6300000226,20150504T000000,380000,4,1.00,1200,2171,1.5,0,0,...,7,1200,0,1933,0,98133,47.7076,-122.342,1130,1598
21581,7853420110,20150504T000000,625000,3,3.00,2780,6000,2.0,0,0,...,9,2780,0,2013,0,98065,47.5184,-121.886,2850,6000

In [ ]:
df.iloc[3:6, 6:10]

   sqft_lot  floors  waterfront  view
3      5000     1.0           0     0
4      8080     1.0           0     0
5    101930     1.0           0     0

In [ ]:
df_q = pd.DataFrame({'A':[34, 78, 54], 'B':[12, 67, 43]}, index=['r1', 'r2', 'r3'])
df_q

     A   B
r1  34  12
r2  78  67
r3  54  43

In [ ]:
df_q.loc['r2':'r3']

     A   B
r2  78  67
r3  54  43

In [ ]:
import pandas as pd
df = pd.read_csv('housing.csv')
df

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,20141013T000000,221900,3,1.00,1180,5650,1.0,0,0,...,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,6414100192,20141209T000000,538000,3,2.25,2570,7242,2.0,0,0,...,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,5631500400,20150225T000000,180000,2,1.00,770,10000,1.0,0,0,...,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,2487200875,20141209T000000,604000,4,3.00,1960,5000,1.0,0,0,...,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,1954400510,20150218T000000,510000,3,2.00,1680,8080,1.0,0,0,...,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21608,263000018,20140521T000000,360000,3,2.50,1530,1131,3.0,0,0,...,8,1530,0,2009,0,98103,47.6993,-122.346,1530,1509
21609,6600060120,20150223T000000,400000,4,2.50,2310,5813,2.0,0,0,...,8,2310,0,2014,0,98146,47.5107,-122.362,1830,7200
21610,1523300141,20140623T000000,402101,2,0.75,1020,1350,2.0,0,0,...,7,1020,0,2009,0,98144,47.5944,-122.299,1020,2007
21611,291310100,20150116T000000,400000,3,2.50,1600,2388,2.0,0,0,...,8,1600,0,2004,0,98027,47.5345,-122.069,1410,1287
21612,1523300157,20141015T000000,325000,2,0.75,1020,1076,2.0,0,0,...,7,1020,0,2008,0,98144,47.5941,-122.299,1020,1357

Find out the value of a Cell in data frame based on conditions


*   1st step- Write the codition and create a filter
*   2nd Step - Use the filter to load matching data from data frame and create another filter
*   3rd step - Use the another filter created in step 2 as index for the df

In [ ]:
filter_1 = df.loc[0:,'price'].max()
filter_2 = df['price'].max() #STEP 1
# print(type(df.where(df['price']==filter_2)))
filter_3 = df['price']== filter_2  #STEP 2
print(f"filter 1 : {filter_1}")
print(f"filter 1 type : {type(filter_1)}")
print(f"filter 2  : {filter_2}")
print(f"filter 2  type : {type(filter_2)}")
print(f"filter 3  : {filter_3}")
print(f"filter 3  type : {type(filter_3)}")
df[filter_3] #STEP 3

<class 'pandas.core.frame.DataFrame'>
filter 1 : 7700000
filter 1 type : <class 'numpy.int64'>
filter 2  : 7700000
filter 2  type : <class 'numpy.int64'>
filter 3  : 0        False
1        False
2        False
3        False
4        False
         ...
21608    False
21609    False
21610    False
21611    False
21612    False
Name: price, Length: 21613, dtype: bool
filter 3  type : <class 'pandas.core.series.Series'>

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
7252,6762700020,20141013T000000,7700000,6,8.0,12050,27600,2.5,0,3,...,13,8570,3480,1910,1987,98102,47.6298,-122.323,3940,8800

In [ ]:
filter_1 = df['grade']== 10
df[filter_1].value_counts()

id          date             price    bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  view  condition  grade  sqft_above  sqft_basement  yr_built  yr_renovated  zipcode  lat      long      sqft_living15  sqft_lot15
11500240    20150428T000000  872750   3         2.50       2870         13695     2.0     0           0     3          10     2870        0              1991      0             98052    47.6944  -122.102  2840           8472          1
5701700640  20140729T000000  849000   3         3.00       2960         42159     2.0     0           0     3          10     2960        0              1995      0             98052    47.7183  -122.100  2640           25209         1
6072800205  20141119T000000  2375000  4         2.50       3220         20251     1.0     0           0     3          10     3220        0              1969      0             98006    47.5692  -122.192  4200           22114         1
6072800170  20150428T000000  2500000  4         4.00       3330         24354     1.0     0           0     4          10     3330        0              1961      0             98006    47.5708  -122.192  3880           25493         1
6065300840  20150501T000000  2850000  4         4.00       5040         17208     1.0     0           0     5          10     2870        2170           1976      0             98006    47.5701  -122.188  4050           18647         1
                                                                                                                                                                                                                                         ..
2481610170  20140609T000000  965000   4         2.25       3160         34560     1.0     0           0     4          10     3160        0              1981      0             98072    47.7337  -122.132  3530           38045         1
2481630030  20150427T000000  965000   4         2.50       3920         41206     2.0     0           0     4          10     3920        0              1988      0             98072    47.7325  -122.132  3780           36562         1
2481630200  20140614T000000  883000   4         2.50       2960         41656     2.0     0           0     3          10     2960        0              1985      0             98072    47.7319  -122.132  3900           35104         1
2481630290  20140626T000000  879000   4         2.75       4230         31747     2.0     0           0     4          10     4230        0              1985      0             98072    47.7310  -122.132  4080           35576         1
9831200172  20150227T000000  1450000  4         3.50       2860         2199      3.0     0           0     3          10     2860        0              2013      0             98102    47.6262  -122.323  1990           1378          1
Name: count, Length: 1134, dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21613 entries, 0 to 21612
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             21613 non-null  int64
 1   date           21613 non-null  object
 2   price          21613 non-null  int64
 3   bedrooms       21613 non-null  int64
 4   bathrooms      21613 non-null  float64
 5   sqft_living    21613 non-null  int64
 6   sqft_lot       21613 non-null  int64
 7   floors         21613 non-null  float64
 8   waterfront     21613 non-null  int64
 9   view           21613 non-null  int64
 10  condition      21613 non-null  int64
 11  grade          21613 non-null  int64
 12  sqft_above     21613 non-null  int64
 13  sqft_basement  21613 non-null  int64
 14  yr_built       21613 non-null  int64
 15  yr_renovated   21613 non-null  int64
 16  zipcode        21613 non-null  int64
 17  lat            21613 non-null  float64
 18  long           21613 non-null  float64
 19  sqft_living15  21613 non-null  int64
 20  sqft_lot15     21613 non-null  int64
dtypes: float64(4), int64(16), object(1)
memory usage: 3.5+ MB

In [ ]:
df.isnull().sum()

id               0
date             0
price            0
bedrooms         0
bathrooms        0
sqft_living      0
sqft_lot         0
floors           0
waterfront       0
view             0
condition        0
grade            0
sqft_above       0
sqft_basement    0
yr_built         0
yr_renovated     0
zipcode          0
lat              0
long             0
sqft_living15    0
sqft_lot15       0
dtype: int64

In [ ]:
filter_1 = df['id']==9126100861
df[filter_1].where(df['waterfront'] == 1).count()

id               0
date             0
price            0
bedrooms         0
bathrooms        0
sqft_living      0
sqft_lot         0
floors           0
waterfront       0
view             0
condition        0
grade            0
sqft_above       0
sqft_basement    0
yr_built         0
yr_renovated     0
zipcode          0
lat              0
long             0
sqft_living15    0
sqft_lot15       0
dtype: int64

In [ ]:
df.head()

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,20141013T000000,221900,3,1.00,1180,5650,1.0,0,0,...,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,6414100192,20141209T000000,538000,3,2.25,2570,7242,2.0,0,0,...,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,5631500400,20150225T000000,180000,2,1.00,770,10000,1.0,0,0,...,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,2487200875,20141209T000000,604000,4,3.00,1960,5000,1.0,0,0,...,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,1954400510,20150218T000000,510000,3,2.00,1680,8080,1.0,0,0,...,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503

In [ ]:
filter_1 = df['view']==3
df[filter_1].count()

id               510
date             510
price            510
bedrooms         510
bathrooms        510
sqft_living      510
sqft_lot         510
floors           510
waterfront       510
view             510
condition        510
grade            510
sqft_above       510
sqft_basement    510
yr_built         510
yr_renovated     510
zipcode          510
lat              510
long             510
sqft_living15    510
sqft_lot15       510
dtype: int64

In [ ]:
df['price'].min()

75000

In [ ]:
filter_1=df['sqft_living'].max()
filter_2=df['sqft_living']==filter_1
df[filter_2]
# df_1 = df[filter_2]
# df_1['zipcode']

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
12777,1225069038,20140505T000000,2280000,7,8.0,13540,307752,3.0,0,4,...,12,9410,4130,1999,0,98053,47.6675,-121.986,4850,217800

In [ ]:
import numpy as np
list_1 = np.arange(0,20)
# list_1 = np.arange(0,20).reshape(4,5)
list_1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
df_1 = pd.DataFrame(list_1)
df_1

    0   1   2   3   4
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19

In [ ]:
ser_1 = pd.Series(list_1)
ser_1

0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
11    11
12    12
13    13
14    14
15    15
16    16
17    17
18    18
19    19
dtype: int64

In [ ]:
dict_1 = {"Age":[30,34,36,37], "Name":['PK', 'LK', 'CK', 'PT']}
dict_1

df_1 = pd.DataFrame(dict_1)
df_1

   Age Name
0   30   PK
1   34   LK
2   36   CK
3   37   PT

In [ ]:
def changeGrade(grade, sqft) :
  if sqft > 0 and sqft < 400 :
    return grade + 1
  elif sqft > 400 :
    return grade + 2
df_1 = df.head()
df_2 = df.apply(lambda x: changeGrade(x['grade'], x['sqft_living']), axis=1)
print(df_1.head(5))
print(df_2.head(5))
print(df.head(5))
# df_2.head()

           id             date   price  bedrooms  bathrooms  sqft_living  \
0  7129300520  20141013T000000  221900         3       1.00         1180
1  6414100192  20141209T000000  538000         3       2.25         2570
2  5631500400  20150225T000000  180000         2       1.00          770
3  2487200875  20141209T000000  604000         4       3.00         1960
4  1954400510  20150218T000000  510000         3       2.00         1680

   sqft_lot  floors  waterfront  view  ...  grade  sqft_above  sqft_basement  \
0      5650     1.0           0     0  ...      7        1180              0
1      7242     2.0           0     0  ...      7        2170            400
2     10000     1.0           0     0  ...      6         770              0
3      5000     1.0           0     0  ...      7        1050            910
4      8080     1.0           0     0  ...      8        1680              0

   yr_built  yr_renovated  zipcode      lat     long  sqft_living15  \
0      1955             0    98178  47.5112 -122.257           1340
1      1951          1991    98125  47.7210 -122.319           1690
2      1933             0    98028  47.7379 -122.233           2720
3      1965             0    98136  47.5208 -122.393           1360
4      1987             0    98074  47.6168 -122.045           1800

   sqft_lot15
0        5650
1        7639
2        8062
3        5000
4        7503

[5 rows x 21 columns]
0     9
1     9
2     8
3     9
4    10
dtype: int64
           id             date   price  bedrooms  bathrooms  sqft_living  \
0  7129300520  20141013T000000  221900         3       1.00         1180
1  6414100192  20141209T000000  538000         3       2.25         2570
2  5631500400  20150225T000000  180000         2       1.00          770
3  2487200875  20141209T000000  604000         4       3.00         1960
4  1954400510  20150218T000000  510000         3       2.00         1680

   sqft_lot  floors  waterfront  view  ...  grade  sqft_above  sqft_basement  \
0      5650     1.0           0     0  ...      7        1180              0
1      7242     2.0           0     0  ...      7        2170            400
2     10000     1.0           0     0  ...      6         770              0
3      5000     1.0           0     0  ...      7        1050            910
4      8080     1.0           0     0  ...      8        1680              0

   yr_built  yr_renovated  zipcode      lat     long  sqft_living15  \
0      1955             0    98178  47.5112 -122.257           1340
1      1951          1991    98125  47.7210 -122.319           1690
2      1933             0    98028  47.7379 -122.233           2720
3      1965             0    98136  47.5208 -122.393           1360
4      1987             0    98074  47.6168 -122.045           1800

   sqft_lot15
0        5650
1        7639
2        8062
3        5000
4        7503

[5 rows x 21 columns]

In [ ]:

df

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,20141013T000000,221900,3,1.00,1180,5650,1.0,0,0,...,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,6414100192,20141209T000000,538000,3,2.25,2570,7242,2.0,0,0,...,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,5631500400,20150225T000000,180000,2,1.00,770,10000,1.0,0,0,...,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,2487200875,20141209T000000,604000,4,3.00,1960,5000,1.0,0,0,...,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,1954400510,20150218T000000,510000,3,2.00,1680,8080,1.0,0,0,...,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21608,263000018,20140521T000000,360000,3,2.50,1530,1131,3.0,0,0,...,8,1530,0,2009,0,98103,47.6993,-122.346,1530,1509
21609,6600060120,20150223T000000,400000,4,2.50,2310,5813,2.0,0,0,...,8,2310,0,2014,0,98146,47.5107,-122.362,1830,7200
21610,1523300141,20140623T000000,402101,2,0.75,1020,1350,2.0,0,0,...,7,1020,0,2009,0,98144,47.5944,-122.299,1020,2007
21611,291310100,20150116T000000,400000,3,2.50,1600,2388,2.0,0,0,...,8,1600,0,2004,0,98027,47.5345,-122.069,1410,1287
21612,1523300157,20141015T000000,325000,2,0.75,1020,1076,2.0,0,0,...,7,1020,0,2008,0,98144,47.5941,-122.299,1020,1357