In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [59]:
df = pd.read_csv('OnlineRetail.csv', encoding='ISO-8859-1')
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  object
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 33.1+ MB

In [4]:
df.describe()

            Quantity      UnitPrice    CustomerID
count  137838.000000  137838.000000  94102.000000
mean        8.943695       5.180769  15292.544048
std       288.015005     106.172683   1739.318647
min    -74215.000000       0.000000  12346.000000
25%         1.000000       1.250000  13869.000000
50%         3.000000       2.460000  15192.000000
75%        10.000000       4.210000  16889.000000
max     74215.000000   16888.020000  18283.000000

# **What is the unique count of the invoice numbers:**

**DO NOT USE THE WHERE CLAUSE** - The result will be in NaN, True, False.

Option 1 : It should be like df[condition], condition = df[actual_condition]
Option 2 : Define "filter" as variable with condition and then use it like df[filter]

Filter can be written with multiple options
1. Using multiple operators like >, < , ==, &, ~, |
2. Using str.contains(), str.startswidth(), str.endswidth() for matching string values
3. using isin() function for matching values from the list

In [35]:
df[df['InvoiceNo'].str.contains('C', na=False)]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
141,C536379,D,Discount,-1,12/1/2010 9:41,27.50,14527.0,United Kingdom
154,C536383,35004C,SET OF 3 COLOURED FLYING DUCKS,-1,12/1/2010 9:49,4.65,15311.0,United Kingdom
235,C536391,22556,PLASTERS IN TIN CIRCUS PARADE,-12,12/1/2010 10:24,1.65,17548.0,United Kingdom
236,C536391,21984,PACK OF 12 PINK PAISLEY TISSUES,-24,12/1/2010 10:24,0.29,17548.0,United Kingdom
237,C536391,21983,PACK OF 12 BLUE PAISLEY TISSUES,-24,12/1/2010 10:24,0.29,17548.0,United Kingdom
...,...,...,...,...,...,...,...,...
540449,C581490,23144,ZINC T-LIGHT HOLDER STARS SMALL,-11,12/9/2011 9:57,0.83,14397.0,United Kingdom
541541,C581499,M,Manual,-1,12/9/2011 10:28,224.69,15498.0,United Kingdom
541715,C581568,21258,VICTORIAN SEWING BOX LARGE,-5,12/9/2011 11:57,10.95,15311.0,United Kingdom
541716,C581569,84978,HANGING HEART JAR T-LIGHT HOLDER,-1,12/9/2011 11:58,1.25,17315.0,United Kingdom
541717,C581569,20979,36 PENCILS TUBE RED RETROSPOT,-5,12/9/2011 11:58,1.25,17315.0,United Kingdom

In [34]:
filter_1 = df['InvoiceNo'].str.contains('C', na=False)
df[filter_1]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
141,C536379,D,Discount,-1,12/1/2010 9:41,27.50,14527.0,United Kingdom
154,C536383,35004C,SET OF 3 COLOURED FLYING DUCKS,-1,12/1/2010 9:49,4.65,15311.0,United Kingdom
235,C536391,22556,PLASTERS IN TIN CIRCUS PARADE,-12,12/1/2010 10:24,1.65,17548.0,United Kingdom
236,C536391,21984,PACK OF 12 PINK PAISLEY TISSUES,-24,12/1/2010 10:24,0.29,17548.0,United Kingdom
237,C536391,21983,PACK OF 12 BLUE PAISLEY TISSUES,-24,12/1/2010 10:24,0.29,17548.0,United Kingdom
...,...,...,...,...,...,...,...,...
540449,C581490,23144,ZINC T-LIGHT HOLDER STARS SMALL,-11,12/9/2011 9:57,0.83,14397.0,United Kingdom
541541,C581499,M,Manual,-1,12/9/2011 10:28,224.69,15498.0,United Kingdom
541715,C581568,21258,VICTORIAN SEWING BOX LARGE,-5,12/9/2011 11:57,10.95,15311.0,United Kingdom
541716,C581569,84978,HANGING HEART JAR T-LIGHT HOLDER,-1,12/9/2011 11:58,1.25,17315.0,United Kingdom
541717,C581569,20979,36 PENCILS TUBE RED RETROSPOT,-5,12/9/2011 11:58,1.25,17315.0,United Kingdom

In [14]:
df['InvoiceNo'].unique().size

25900

# **How many people bought “PARTY BUNTING”.:**

In [36]:
df[df['Description']=='PARTY BUNTING']

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
5535,536864,47566,PARTY BUNTING,1,12/3/2010 11:27,9.32,NaN,United Kingdom
5656,536865,47566,PARTY BUNTING,3,12/3/2010 11:28,9.32,NaN,United Kingdom
6022,536876,47566,PARTY BUNTING,2,12/3/2010 11:36,8.47,NaN,United Kingdom
6572,536956,47566,PARTY BUNTING,5,12/3/2010 12:43,4.65,14210.0,United Kingdom
7904,537065,47566,PARTY BUNTING,5,12/5/2010 11:57,4.65,12567.0,France
...,...,...,...,...,...,...,...,...
537784,581345,47566,PARTY BUNTING,5,12/8/2011 12:15,4.95,17315.0,United Kingdom
538825,581417,47566,PARTY BUNTING,8,12/8/2011 15:01,4.95,13013.0,United Kingdom
539027,581426,47566,PARTY BUNTING,1,12/8/2011 15:31,4.95,17757.0,United Kingdom
540534,581492,47566,PARTY BUNTING,2,12/9/2011 10:03,10.79,NaN,United Kingdom
541318,581497,47566,PARTY BUNTING,5,12/9/2011 10:23,10.79,NaN,United Kingdom

# **How many people bought “WHITE HANGING HEART T-LIGHT HOLDER”.**

In [60]:
filtered_df = df[df['Description']=='WHITE HANGING HEART T-LIGHT HOLDER'].reset_index(drop=True)
filtered_df

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536373,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 9:02,2.55,17850.0,United Kingdom
2,536375,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 9:32,2.55,17850.0,United Kingdom
3,536390,85123A,WHITE HANGING HEART T-LIGHT HOLDER,64,12/1/2010 10:19,2.55,17511.0,United Kingdom
4,536394,85123A,WHITE HANGING HEART T-LIGHT HOLDER,32,12/1/2010 10:39,2.55,13408.0,United Kingdom
...,...,...,...,...,...,...,...,...
2364,581246,85123A,WHITE HANGING HEART T-LIGHT HOLDER,1,12/8/2011 10:59,2.95,15453.0,United Kingdom
2365,581253,85123A,WHITE HANGING HEART T-LIGHT HOLDER,2,12/8/2011 11:15,2.95,16891.0,United Kingdom
2366,581356,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/8/2011 12:28,2.95,17830.0,United Kingdom
2367,581452,85123A,WHITE HANGING HEART T-LIGHT HOLDER,32,12/8/2011 18:03,2.55,17675.0,United Kingdom
2368,581472,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/8/2011 19:55,2.95,15796.0,United Kingdom

# **how many unique people are from “UNITED KINGDOM”.**


As the term "UNIQUE" coming here indicates that we have issues with the data.So perform data cleaning.

1. Look for isna and clean the records

In [68]:
df.isna().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [69]:
df.dropna(inplace=True)

In [70]:
df.isna().sum()

InvoiceNo      0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
UnitPrice      0
CustomerID     0
Country        0
dtype: int64

In [72]:
df[df['Country']=='United Kingdom']

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
541889,581585,22466,FAIRY TALE COTTAGE NIGHT LIGHT,12,12/9/2011 12:31,1.95,15804.0,United Kingdom
541890,581586,22061,LARGE CAKE STAND HANGING STRAWBERY,8,12/9/2011 12:49,2.95,13113.0,United Kingdom
541891,581586,23275,SET OF 3 HANGING OWLS OLLIE BEAK,24,12/9/2011 12:49,1.25,13113.0,United Kingdom
541892,581586,21217,RED RETROSPOT ROUND CAKE TINS,24,12/9/2011 12:49,8.95,13113.0,United Kingdom
541893,581586,20685,DOORMAT RED RETROSPOT,10,12/9/2011 12:49,7.08,13113.0,United Kingdom

# **Which customer(CustomerID) has done highest transaction in thedataset.**

In [77]:
# Approach 1 : calculate the total amount for each transaction
df['TotalAmount'] = df['Quantity'] * df['UnitPrice']

# Now each customer might have done multiple transactions
df.groupby('CustomerID')['TotalAmount'].sum().sort_values(ascending=False)

CustomerID
14646.0    279489.02
18102.0    256438.49
17450.0    187482.17
14911.0    132572.62
12415.0    123725.45
             ...
12503.0     -1126.00
17603.0     -1165.30
14213.0     -1192.20
15369.0     -1592.49
17448.0     -4287.63
Name: TotalAmount, Length: 4372, dtype: float64

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalAmount
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom,15.30
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom,20.34
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom,22.00
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom,20.34
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom,20.34
...,...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,12/9/2011 12:50,0.85,12680.0,France,10.20
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,12/9/2011 12:50,2.10,12680.0,France,12.60
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,12/9/2011 12:50,4.15,12680.0,France,16.60
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,12/9/2011 12:50,4.15,12680.0,France,16.60
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,12/9/2011 12:50,4.95,12680.0,France,14.85

In [ ]:
# prompt: Which customer(CustomerID) has done highest transaction in the dataset

# Calculate total amount for each transaction
df['TotalAmount'] = df['Quantity'] * df['UnitPrice']

# Group by CustomerID and sum the total amount for each customer
customer_total = df.groupby('CustomerID')['TotalAmount'].sum()

# Find the customer with the highest total transaction amount
customer_with_highest_transaction = customer_total.idxmax()

print(f"The customer with the highest total transaction amount is: {customer_with_highest_transaction}")

customer_total.sort_values(ascending=False)

The customer with the highest total transaction amount is: 14646.0

CustomerID
14646.0    279489.02
18102.0    256438.49
17450.0    187482.17
14911.0    132572.62
12415.0    123725.45
             ...
12503.0     -1126.00
17603.0     -1165.30
14213.0     -1192.20
15369.0     -1592.49
17448.0     -4287.63
Name: TotalAmount, Length: 4372, dtype: float64

Average amount of transaction

In [ ]:
df

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalAmount
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom,15.30
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom,20.34
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom,22.00
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom,20.34
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom,20.34
...,...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,12/9/2011 12:50,0.85,12680.0,France,10.20
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,12/9/2011 12:50,2.10,12680.0,France,12.60
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,12/9/2011 12:50,4.15,12680.0,France,16.60
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,12/9/2011 12:50,4.15,12680.0,France,16.60
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,12/9/2011 12:50,4.95,12680.0,France,14.85

In [ ]:
total_transaction = df['TotalAmount'].sum()
total_transaction

9747747.933999998

In [ ]:
total_transaction/df['TotalAmount'].count()

17.98779487699964

In [ ]:
# cancelled_invoces = df.where(df['InvoiceNo'].str.contains("C", na=False)).value_counts()
# cancelled_invoces
sucess_invoces = df.where(~df['InvoiceNo'].str.contains("C", na=False))
sucess_invoces

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalAmount
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6.0,12/1/2010 8:26,2.55,17850.0,United Kingdom,15.30
1,536365,71053,WHITE METAL LANTERN,6.0,12/1/2010 8:26,3.39,17850.0,United Kingdom,20.34
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8.0,12/1/2010 8:26,2.75,17850.0,United Kingdom,22.00
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6.0,12/1/2010 8:26,3.39,17850.0,United Kingdom,20.34
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6.0,12/1/2010 8:26,3.39,17850.0,United Kingdom,20.34
...,...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12.0,12/9/2011 12:50,0.85,12680.0,France,10.20
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6.0,12/9/2011 12:50,2.10,12680.0,France,12.60
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4.0,12/9/2011 12:50,4.15,12680.0,France,16.60
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4.0,12/9/2011 12:50,4.15,12680.0,France,16.60
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3.0,12/9/2011 12:50,4.95,12680.0,France,14.85

In [ ]:
sucess_invoces['TotalAmount'].sum()/sucess_invoces['TotalAmount'].count()

19.985243585964508

How many unique people are from “UNITED KINGDOM”?

In [ ]:
unique_customers = df['CustomerID'].unique()
unique_customers.size

4373

In [ ]:
# prompt: how many unique people are from “UNITED KINGDOM”.

# How many unique people are from “UNITED KINGDOM”?
uk_customers = df[df['Country'] == 'United Kingdom']
print(f"The number of unique customers from the UK is: {uk_customers}")

The number of unique customers from the UK is:        InvoiceNo StockCode                          Description  Quantity  \
0         536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6
1         536365     71053                  WHITE METAL LANTERN         6
2         536365    84406B       CREAM CUPID HEARTS COAT HANGER         8
3         536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6
4         536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6
...          ...       ...                                  ...       ...
541889    581585     22466       FAIRY TALE COTTAGE NIGHT LIGHT        12
541890    581586     22061  LARGE CAKE STAND  HANGING STRAWBERY         8
541891    581586     23275     SET OF 3 HANGING OWLS OLLIE BEAK        24
541892    581586     21217        RED RETROSPOT ROUND CAKE TINS        24
541893    581586     20685                DOORMAT RED RETROSPOT        10

            InvoiceDate  UnitPrice  CustomerID         Country  TotalAmount
0        12/1/2010 8:26       2.55     17850.0  United Kingdom        15.30
1        12/1/2010 8:26       3.39     17850.0  United Kingdom        20.34
2        12/1/2010 8:26       2.75     17850.0  United Kingdom        22.00
3        12/1/2010 8:26       3.39     17850.0  United Kingdom        20.34
4        12/1/2010 8:26       3.39     17850.0  United Kingdom        20.34
...                 ...        ...         ...             ...          ...
541889  12/9/2011 12:31       1.95     15804.0  United Kingdom        23.40
541890  12/9/2011 12:49       2.95     13113.0  United Kingdom        23.60
541891  12/9/2011 12:49       1.25     13113.0  United Kingdom        30.00
541892  12/9/2011 12:49       8.95     13113.0  United Kingdom       214.80
541893  12/9/2011 12:49       7.08     13113.0  United Kingdom        70.80

[495478 rows x 9 columns]

In [ ]:
uk_customers

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalAmount
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom,15.30
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom,20.34
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom,22.00
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom,20.34
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom,20.34
...,...,...,...,...,...,...,...,...,...
541889,581585,22466,FAIRY TALE COTTAGE NIGHT LIGHT,12,12/9/2011 12:31,1.95,15804.0,United Kingdom,23.40
541890,581586,22061,LARGE CAKE STAND HANGING STRAWBERY,8,12/9/2011 12:49,2.95,13113.0,United Kingdom,23.60
541891,581586,23275,SET OF 3 HANGING OWLS OLLIE BEAK,24,12/9/2011 12:49,1.25,13113.0,United Kingdom,30.00
541892,581586,21217,RED RETROSPOT ROUND CAKE TINS,24,12/9/2011 12:49,8.95,13113.0,United Kingdom,214.80
541893,581586,20685,DOORMAT RED RETROSPOT,10,12/9/2011 12:49,7.08,13113.0,United Kingdom,70.80

In [ ]:
uninue_customers = uk_customers['CustomerID'].unique()
uninue_customers.size

3951

In [ ]:
unique_customers = df['CustomerID'].unique()
unique_customers.size

4373

In [ ]:
# prompt: How many people bought “WHITE HANGING HEART T-LIGHT HOLDER”

# How many people bought “WHITE HANGING HEART T-LIGHT HOLDER”
white_hanging_heart_buyers = df[df['Description'] == 'WHITE HANGING HEART T-LIGHT HOLDER']
print(f"The number of people who bought 'WHITE HANGING HEART T-LIGHT HOLDER' is: {white_hanging_heart_buyers}")

The number of people who bought 'WHITE HANGING HEART T-LIGHT HOLDER' is:        InvoiceNo StockCode                         Description  Quantity  \
0         536365    85123A  WHITE HANGING HEART T-LIGHT HOLDER         6
49        536373    85123A  WHITE HANGING HEART T-LIGHT HOLDER         6
66        536375    85123A  WHITE HANGING HEART T-LIGHT HOLDER         6
220       536390    85123A  WHITE HANGING HEART T-LIGHT HOLDER        64
262       536394    85123A  WHITE HANGING HEART T-LIGHT HOLDER        32
...          ...       ...                                 ...       ...
537291    581246    85123A  WHITE HANGING HEART T-LIGHT HOLDER         1
537326    581253    85123A  WHITE HANGING HEART T-LIGHT HOLDER         2
537852    581356    85123A  WHITE HANGING HEART T-LIGHT HOLDER         6
539979    581452    85123A  WHITE HANGING HEART T-LIGHT HOLDER        32
540217    581472    85123A  WHITE HANGING HEART T-LIGHT HOLDER         6

            InvoiceDate  UnitPrice  CustomerID         Country  TotalAmount
0        12/1/2010 8:26       2.55     17850.0  United Kingdom        15.30
49       12/1/2010 9:02       2.55     17850.0  United Kingdom        15.30
66       12/1/2010 9:32       2.55     17850.0  United Kingdom        15.30
220     12/1/2010 10:19       2.55     17511.0  United Kingdom       163.20
262     12/1/2010 10:39       2.55     13408.0  United Kingdom        81.60
...                 ...        ...         ...             ...          ...
537291  12/8/2011 10:59       2.95     15453.0  United Kingdom         2.95
537326  12/8/2011 11:15       2.95     16891.0  United Kingdom         5.90
537852  12/8/2011 12:28       2.95     17830.0  United Kingdom        17.70
539979  12/8/2011 18:03       2.55     17675.0  United Kingdom        81.60
540217  12/8/2011 19:55       2.95     15796.0  United Kingdom        17.70

[2369 rows x 9 columns]

In [ ]:
# prompt: How many people bought “PARTY BUNTING”.

party_bunting_buyers = df[df['Description'] == 'PARTY BUNTING']
print(f"The number of people who bought 'PARTY BUNTING' is: {party_bunting_buyers}")

The number of people who bought 'PARTY BUNTING' is:        InvoiceNo StockCode    Description  Quantity      InvoiceDate  \
5535      536864     47566  PARTY BUNTING         1  12/3/2010 11:27
5656      536865     47566  PARTY BUNTING         3  12/3/2010 11:28
6022      536876     47566  PARTY BUNTING         2  12/3/2010 11:36
6572      536956     47566  PARTY BUNTING         5  12/3/2010 12:43
7904      537065     47566  PARTY BUNTING         5  12/5/2010 11:57
...          ...       ...            ...       ...              ...
537784    581345     47566  PARTY BUNTING         5  12/8/2011 12:15
538825    581417     47566  PARTY BUNTING         8  12/8/2011 15:01
539027    581426     47566  PARTY BUNTING         1  12/8/2011 15:31
540534    581492     47566  PARTY BUNTING         2  12/9/2011 10:03
541318    581497     47566  PARTY BUNTING         5  12/9/2011 10:23

        UnitPrice  CustomerID         Country  TotalAmount
5535         9.32         NaN  United Kingdom         9.32
5656         9.32         NaN  United Kingdom        27.96
6022         8.47         NaN  United Kingdom        16.94
6572         4.65     14210.0  United Kingdom        23.25
7904         4.65     12567.0          France        23.25
...           ...         ...             ...          ...
537784       4.95     17315.0  United Kingdom        24.75
538825       4.95     13013.0  United Kingdom        39.60
539027       4.95     17757.0  United Kingdom         4.95
540534      10.79         NaN  United Kingdom        21.58
541318      10.79         NaN  United Kingdom        53.95

[1727 rows x 9 columns]

In [ ]:
# prompt: What is the frequently bought item in the dataset

# Find the most frequently bought item
most_frequent_item = df['Description'].mode()[0]

most_frequent_item
# print(f"The most frequently bought item is: {most_frequent_item}")

'WHITE HANGING HEART T-LIGHT HOLDER'

In [ ]:
df.isna().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
TotalAmount         0
dtype: int64

In [ ]:
df_cleaned = df.dropna()
df_cleaned

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalAmount
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom,15.30
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom,20.34
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom,22.00
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom,20.34
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom,20.34
...,...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,12/9/2011 12:50,0.85,12680.0,France,10.20
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,12/9/2011 12:50,2.10,12680.0,France,12.60
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,12/9/2011 12:50,4.15,12680.0,France,16.60
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,12/9/2011 12:50,4.15,12680.0,France,16.60
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,12/9/2011 12:50,4.95,12680.0,France,14.85

In [ ]:
df_cleaned.isna().sum()

InvoiceNo      0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
UnitPrice      0
CustomerID     0
Country        0
TotalAmount    0
dtype: int64

In [ ]:
df_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
Index: 406829 entries, 0 to 541908
Data columns (total 9 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    406829 non-null  object
 1   StockCode    406829 non-null  object
 2   Description  406829 non-null  object
 3   Quantity     406829 non-null  int64
 4   InvoiceDate  406829 non-null  object
 5   UnitPrice    406829 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      406829 non-null  object
 8   TotalAmount  406829 non-null  float64
dtypes: float64(3), int64(1), object(5)
memory usage: 31.0+ MB

In [ ]:
uk_customers = df_cleaned.where(df_cleaned['Country']=='United Kingdom')

In [ ]:
uk_customers.dropna()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalAmount
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6.0,12/1/2010 8:26,2.55,17850.0,United Kingdom,15.30
1,536365,71053,WHITE METAL LANTERN,6.0,12/1/2010 8:26,3.39,17850.0,United Kingdom,20.34
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8.0,12/1/2010 8:26,2.75,17850.0,United Kingdom,22.00
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6.0,12/1/2010 8:26,3.39,17850.0,United Kingdom,20.34
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6.0,12/1/2010 8:26,3.39,17850.0,United Kingdom,20.34
...,...,...,...,...,...,...,...,...,...
541889,581585,22466,FAIRY TALE COTTAGE NIGHT LIGHT,12.0,12/9/2011 12:31,1.95,15804.0,United Kingdom,23.40
541890,581586,22061,LARGE CAKE STAND HANGING STRAWBERY,8.0,12/9/2011 12:49,2.95,13113.0,United Kingdom,23.60
541891,581586,23275,SET OF 3 HANGING OWLS OLLIE BEAK,24.0,12/9/2011 12:49,1.25,13113.0,United Kingdom,30.00
541892,581586,21217,RED RETROSPOT ROUND CAKE TINS,24.0,12/9/2011 12:49,8.95,13113.0,United Kingdom,214.80
541893,581586,20685,DOORMAT RED RETROSPOT,10.0,12/9/2011 12:49,7.08,13113.0,United Kingdom,70.80

In [ ]:
only_PARTY_BUNTING_buyers = df_cleaned.where(df_cleaned['Description'].str.contains('TEA TIME PARTY BUNTING', case=False))
only_PARTY_BUNTING_buyers.dropna()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalAmount
3614,536638,47566B,TEA TIME PARTY BUNTING,5.0,12/2/2010 11:41,4.65,16244.0,United Kingdom,23.25
8759,537144,47566B,TEA TIME PARTY BUNTING,1.0,12/5/2010 13:00,4.65,15880.0,United Kingdom,4.65
9250,537196,47566B,TEA TIME PARTY BUNTING,3.0,12/5/2010 13:55,4.65,15426.0,United Kingdom,13.95
9768,537216,47566B,TEA TIME PARTY BUNTING,8.0,12/5/2010 15:40,4.65,15502.0,United Kingdom,37.20
13110,537420,47566B,TEA TIME PARTY BUNTING,5.0,12/6/2010 15:18,4.65,17519.0,United Kingdom,23.25
...,...,...,...,...,...,...,...,...,...
453830,575491,47566B,TEA TIME PARTY BUNTING,2.0,11/9/2011 17:47,4.95,15531.0,United Kingdom,9.90
465679,576249,47566B,TEA TIME PARTY BUNTING,1.0,11/14/2011 13:47,4.95,17811.0,United Kingdom,4.95
485059,577549,47566B,TEA TIME PARTY BUNTING,2.0,11/20/2011 15:00,4.95,17841.0,United Kingdom,9.90
510054,579414,47566B,TEA TIME PARTY BUNTING,1.0,11/29/2011 12:52,4.95,14719.0,United Kingdom,4.95
523205,580503,47566B,TEA TIME PARTY BUNTING,1.0,12/4/2011 13:20,4.95,13956.0,United Kingdom,4.95

In [ ]:
count_of_party_bunting = df.where(df['Description'].str.contains("PARTY BUNTING", na=False)).value_counts()
count_of_party_bunting

InvoiceNo  StockCode  Description             Quantity  InvoiceDate       UnitPrice  CustomerID  Country
552654     47566      PARTY BUNTING            1.0      5/10/2011 14:20   4.95       15756.0     United Kingdom    2
545658     47566B     TEA TIME PARTY BUNTING   1.0      3/4/2011 14:13    4.95       14670.0     United Kingdom    2
542213     47566      PARTY BUNTING            1.0      1/26/2011 12:15   4.65       13837.0     United Kingdom    2
566786     47566      PARTY BUNTING            4.0      9/15/2011 10:29   4.95       13518.0     United Kingdom    2
558232     47566B     TEA TIME PARTY BUNTING   1.0      6/27/2011 14:30   4.95       17841.0     United Kingdom    2
                                                                                                                  ..
551721     47566      PARTY BUNTING            1.0      5/3/2011 16:49    4.95       14711.0     United Kingdom    1
551696     47566      PARTY BUNTING            8.0      5/3/2011 13:39    4.95       14110.0     United Kingdom    1
551653     47566      PARTY BUNTING            8.0      5/3/2011 12:03    4.95       13282.0     United Kingdom    1
551650     47566      PARTY BUNTING            12.0     5/3/2011 12:02    4.95       13089.0     United Kingdom    1
C578832    47566      PARTY BUNTING           -6.0      11/25/2011 15:18  4.95       13069.0     United Kingdom    1
Name: count, Length: 1730, dtype: int64

In [ ]:
count_of_party_bunting.nunique()

2

In [ ]:
count.where(count['count']==2).value_counts()

count
2.0      7
Name: count, dtype: int64

In [ ]:
count_of_party_lightholder = df.where(df['Description'].str.contains("WHITE HANGING HEART T-LIGHT HOLDER", na=False)).value_counts()
count_of_party_lightholder

InvoiceNo  StockCode  Description                         Quantity  InvoiceDate       UnitPrice  CustomerID  Country
560555     85123A     WHITE HANGING HEART T-LIGHT HOLDER   1.0      7/19/2011 13:01   2.95       14178.0     United Kingdom    3
560385     85123A     WHITE HANGING HEART T-LIGHT HOLDER   1.0      7/18/2011 12:53   2.95       14583.0     United Kingdom    2
542239     85123A     WHITE HANGING HEART T-LIGHT HOLDER   2.0      1/26/2011 14:35   2.95       17786.0     United Kingdom    2
578255     85123A     WHITE HANGING HEART T-LIGHT HOLDER   1.0      11/23/2011 12:58  2.95       14675.0     United Kingdom    2
569527     85123A     WHITE HANGING HEART T-LIGHT HOLDER   1.0      10/4/2011 14:53   2.95       12512.0     Israel            2
                                                                                                                              ..
548865     85123A     WHITE HANGING HEART T-LIGHT HOLDER   6.0      4/4/2011 14:09    2.95       14747.0     United Kingdom    1
548860     85123A     WHITE HANGING HEART T-LIGHT HOLDER   2.0      4/4/2011 13:38    2.95       13263.0     United Kingdom    1
548808     85123A     WHITE HANGING HEART T-LIGHT HOLDER   3.0      4/4/2011 12:55    2.95       17774.0     United Kingdom    1
548749     85123A     WHITE HANGING HEART T-LIGHT HOLDER   6.0      4/4/2011 12:29    2.95       13004.0     United Kingdom    1
C580805    85123A     WHITE HANGING HEART T-LIGHT HOLDER  -1.0      12/6/2011 11:23   2.95       16764.0     United Kingdom    1
Name: count, Length: 2058, dtype: int64

In [ ]:
des = count_of_party_lightholder.groupby('CustomerID').size().sort_values(ascending=False)

In [ ]:
des.head(10)

CustomerID
14911.0    34
13263.0    23
17841.0    20
17850.0    17
17675.0    16
17511.0    15
18118.0    15
13798.0    15
15005.0    14
15856.0    14
Name: count, dtype: int64

In [ ]:
des.describe()

count    858.000000
mean       2.398601
std        2.625092
min        1.000000
25%        1.000000
50%        1.000000
75%        3.000000
max       34.000000
Name: count, dtype: float64

In [ ]:
# prompt: Create a DataFrame with unique description of item ,count of the item ,total amount paid for the item from dataframe df. Then get the least purchased item.

# Create a DataFrame with unique descriptions, counts, and total amounts
item_summary = df.groupby('Description').agg({'Quantity': 'sum', 'UnitPrice': 'sum'})
item_summary = item_summary.rename(columns={'Quantity': 'Count', 'UnitPrice': 'TotalAmount'})

# Get the least purchased item
least_purchased_item = item_summary['Count'].idxmin()

print(f"The least purchased item is: {least_purchased_item}")

The least purchased item is: printing smudges/thrown away

In [ ]:
total_quantity = df_cleaned.groupby('Description')['Quantity'].sum()
total_quantity.sort_values(ascending=False)

Description
WORLD WAR 2 GLIDERS ASSTD DESIGNS      53215
JUMBO BAG RED RETROSPOT                45066
ASSORTED COLOUR BIRD ORNAMENT          35314
WHITE HANGING HEART T-LIGHT HOLDER     34147
PACK OF 72 RETROSPOT CAKE CASES        33409
                                       ...
PINK POODLE HANGING DECORATION           -12
CRUK Commission                          -16
ASSORTED TUTTI FRUTTI ROUND BOX          -24
Discount                               -1194
ROTATING SILVER ANGELS T-LIGHT HLDR    -1460
Name: Quantity, Length: 3896, dtype: int64

In [ ]:
# Create a DataFrame with unique descriptions, counts, and total amounts
item_summary = df.groupby('Description')

In [ ]:
item_summary