In [55]:
import numpy as np
import pandas as pd

data = pd.read_csv('mtcars2.csv')
data.head()

,S.No,Unnamed: 1,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,1,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,2,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,3,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,4,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,5,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

In [2]:
data.drop('S.No', axis=1, inplace=True)
data.head()

,Unnamed: 1,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

In [3]:
data.rename(columns={'Unnamed: 1': 'model'}, inplace=True)
data.head()

,model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

In [4]:
data.sort_values(by='model', inplace=True)
data.head()

,model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
22,AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2
14,Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4
23,Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4
16,Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1

In [9]:
data.sort_values(by=['cyl', 'hp', 'mpg'], ascending= True, inplace=True)
data.head(20)

,model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
18,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2
7,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2
19,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1
25,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,NaN,1,1,4,1
17,Fiat 128,32.4,4,78.7,66,4.08,2.200,NaN,1,1,4,1
26,Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
8,Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2
20,Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1
31,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2
27,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2
5,Valiant,18.1,6,225.0,105,2.76,3.460,NaN,1,0,3,1
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
10,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4
9,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4
29,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6
22,AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2
21,Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2

In [10]:
data

,model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
18,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2
7,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2
19,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1
25,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,NaN,1,1,4,1
17,Fiat 128,32.4,4,78.7,66,4.08,2.200,NaN,1,1,4,1
26,Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
8,Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2
20,Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1
31,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2
27,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2
5,Valiant,18.1,6,225.0,105,2.76,3.460,NaN,1,0,3,1
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
10,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4
9,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4
29,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6
22,AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2
21,Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2
24,Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2
13,Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3
11,Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3
12,Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3
14,Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4
15,Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4
16,Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4
23,Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4
6,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
28,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4
30,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8

In [12]:
data.sort_index()

,model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2
5,Valiant,18.1,6,225.0,105,2.76,3.460,NaN,1,0,3,1
6,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
7,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2
8,Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2
9,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4
10,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4
11,Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3
12,Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3
13,Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3
14,Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4
15,Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4
16,Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4
17,Fiat 128,32.4,4,78.7,66,4.08,2.200,NaN,1,1,4,1
18,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2
19,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1
20,Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1
21,Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2
22,AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2
23,Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4
24,Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2
25,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,NaN,1,1,4,1
26,Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2
27,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2
28,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4
29,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6
30,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8
31,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2

In [13]:
data.set_index('model')

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
model,,,,,,,,,,,
Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2
Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2
Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1
Fiat X1-9,27.3,4,79.0,66,4.08,1.935,NaN,1,1,4,1
Fiat 128,32.4,4,78.7,66,4.08,2.200,NaN,1,1,4,1
Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2
Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1
Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2
Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2
Valiant,18.1,6,225.0,105,2.76,3.460,NaN,1,0,3,1
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4
Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4
Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6
AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2
Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2
Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2
Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3
Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3
Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3
Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4
Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4
Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4
Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4
Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4
Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8

In [14]:
data.reset_index()

,index,model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,18,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2
1,7,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2
2,19,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1
3,25,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,NaN,1,1,4,1
4,17,Fiat 128,32.4,4,78.7,66,4.08,2.200,NaN,1,1,4,1
5,26,Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2
6,2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
7,8,Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2
8,20,Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1
9,31,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2
10,27,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2
11,5,Valiant,18.1,6,225.0,105,2.76,3.460,NaN,1,0,3,1
12,0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
13,1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
14,3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
15,10,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4
16,9,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4
17,29,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6
18,22,AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2
19,21,Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2
20,4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2
21,24,Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2
22,13,Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3
23,11,Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3
24,12,Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3
25,14,Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4
26,15,Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4
27,16,Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4
28,23,Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4
29,6,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
30,28,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4
31,30,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8

In [15]:
data.reset_index(drop=True)

,model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2
1,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2
2,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1
3,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,NaN,1,1,4,1
4,Fiat 128,32.4,4,78.7,66,4.08,2.200,NaN,1,1,4,1
5,Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2
6,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
7,Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2
8,Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1
9,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2
10,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2
11,Valiant,18.1,6,225.0,105,2.76,3.460,NaN,1,0,3,1
12,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
13,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
14,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
15,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4
16,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4
17,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6
18,AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2
19,Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2
20,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2
21,Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2
22,Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3
23,Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3
24,Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3
25,Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4
26,Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4
27,Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4
28,Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4
29,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
30,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4
31,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8

AttributeError: 'DataFrame' object has no attribute 'append'

In [19]:
import pandas as pd

# Example data
data = {
    'Name': ['Alice', 'Bob'],
    'Age': [25, 30],
    'City': ['New York', 'Los Angeles']
}

df = pd.DataFrame(data)
print(df)

    Name  Age         City
0  Alice   25     New York
1    Bob   30  Los Angeles

In [22]:
# Adding a single row
new_row = {'Name': 'Charlie', 'Age': 35, 'City': 'Chicago'}
# df = df.append(new_row, ignore_index=True)  # Deprecated in new pandas

# Recommended in recent versions of pandas:
df = pd.concat([df, pd.DataFrame([new_row])], ignore_index=True)
df

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago
3  Charlie   35      Chicago
4  Charlie   35      Chicago

In [25]:
data = pd.read_csv('mtcars2.csv')
data.head()

,S.No,Unnamed: 1,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,1,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,2,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,3,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,4,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,5,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

In [35]:
filter_1 = data['cyl'] == 4
print(filter_1.dtype)

bool

In [37]:
mask = np.logical_and(data['cyl']> 4, data['hp'] > 100)
data[mask]

,S.No,Unnamed: 1,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,1,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,2,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
3,4,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,5,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2
5,6,Valiant,18.1,6,225.0,105,2.76,3.460,NaN,1,0,3,1
6,7,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
9,10,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4
10,11,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4
11,12,Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3
12,13,Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3
13,14,Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3
14,15,Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4
15,16,Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4
16,17,Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4
21,22,Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2
22,23,AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2
23,24,Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4
24,25,Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2
28,29,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4
29,30,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6
30,31,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8

In [40]:
data.query('(cyl > 4 and hp > 100) | mpg > 20')

,S.No,Unnamed: 1,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,1,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,2,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,3,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,4,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,5,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2
5,6,Valiant,18.1,6,225.0,105,2.76,3.460,NaN,1,0,3,1
6,7,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
7,8,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2
8,9,Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2
9,10,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4
10,11,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4
11,12,Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3
12,13,Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3
13,14,Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3
14,15,Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4
15,16,Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4
16,17,Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4
17,18,Fiat 128,32.4,4,78.7,66,4.08,2.200,NaN,1,1,4,1
18,19,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2
19,20,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1
20,21,Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1
21,22,Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2
22,23,AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2
23,24,Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4
24,25,Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2
25,26,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,NaN,1,1,4,1
26,27,Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2
27,28,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2
28,29,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4
29,30,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6
30,31,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8
31,32,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2

In [42]:
data.query('mpg > 20')['hp'].mean()

np.float64(88.5)

In [43]:
data.groupby('cyl')['hp'].mean()

cyl
4     82.636364
6    122.285714
8    209.214286
Name: hp, dtype: float64

In [44]:
data.groupby(['cyl', 'hp'])['mpg'].mean()

cyl  hp
4    52     30.400000
     62     24.400000
     65     33.900000
     66     29.850000
     91     26.000000
     93     22.800000
     95     22.800000
     97     21.500000
     109    21.400000
     113    30.400000
6    105    18.100000
     110    21.133333
     123    18.500000
     175    19.700000
8    150    15.350000
     175    18.950000
     180    16.300000
     205    10.400000
     215    10.400000
     230    14.700000
     245    13.800000
     264    15.800000
     335    15.000000
Name: mpg, dtype: float64

In [49]:
data.groupby(['cyl', 'hp'])['mpg'].mean().sort_index(ascending=False)

cyl  hp
8    335    15.000000
     264    15.800000
     245    13.800000
     230    14.700000
     215    10.400000
     205    10.400000
     180    16.300000
     175    18.950000
     150    15.350000
6    175    19.700000
     123    18.500000
     110    21.133333
     105    18.100000
4    113    30.400000
     109    21.400000
     97     21.500000
     95     22.800000
     93     22.800000
     91     26.000000
     66     29.850000
     65     33.900000
     62     24.400000
     52     30.400000
Name: mpg, dtype: float64

In [46]:
data.groupby('cyl').agg(mean_hp=('hp', 'mean'), max_mpg=('mpg', 'max'))

        mean_hp  max_mpg
cyl
4     82.636364     33.9
6    122.285714     21.4
8    209.214286     19.2

In [50]:
data.head(5)

,S.No,Unnamed: 1,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,1,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,2,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,3,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,4,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,5,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

In [53]:
data.head(20).pivot_table(values='mpg', index='cyl', columns=['hp', 'am'], aggfunc='mean')

hp    52    62    65    66    93    95    105   110         123   175   180  \
am      1     0     1     1     1     0     0     0     1     0     0     0
cyl
4    30.4  24.4  33.9  32.4  22.8  22.8   NaN   NaN   NaN   NaN   NaN   NaN
6     NaN   NaN   NaN   NaN   NaN   NaN  18.1  21.4  21.0  18.5   NaN   NaN
8     NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  18.7  16.3

hp    205   215   230   245
am      0     0     0     0
cyl
4     NaN   NaN   NaN   NaN
6     NaN   NaN   NaN   NaN
8    10.4  10.4  14.7  14.3

In [54]:
data

,S.No,Unnamed: 1,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,1,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,2,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,3,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,4,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,5,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2
5,6,Valiant,18.1,6,225.0,105,2.76,3.460,NaN,1,0,3,1
6,7,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
7,8,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2
8,9,Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2
9,10,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4
10,11,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4
11,12,Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3
12,13,Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3
13,14,Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3
14,15,Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4
15,16,Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4
16,17,Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4
17,18,Fiat 128,32.4,4,78.7,66,4.08,2.200,NaN,1,1,4,1
18,19,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2
19,20,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1
20,21,Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1
21,22,Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2
22,23,AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2
23,24,Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4
24,25,Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2
25,26,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,NaN,1,1,4,1
26,27,Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2
27,28,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2
28,29,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4
29,30,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6
30,31,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8
31,32,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2