### For Colab Users, to upload the data

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving nba_final.csv to nba_final.csv

### **1. Import the required packages**

In [ ]:
import numpy as np
import pandas as pd

#packages for machine learning process
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, roc_auc_score
from sklearn.preprocessing import StandardScaler

### **2. Reading and Exploring the data**

In [ ]:
data = pd.read_csv('nba_final.csv')

In [ ]:
data.head()

,Rk,Player.x,Player_ID,Pos1,Pos2,Age,Tm,G,GS,MP,...,Conference,Role,Fvot,FRank,Pvot,PRank,Mvot,MRank,Score,Play
0,170,A.J. Hammons,hammoaj01,C,NaN,24,DAL,22,0,7.4,...,West,Front,786,123,NaN,NaN,NaN,NaN,83.5,No
1,58,Aaron Brooks,brookaa01,PG,NaN,32,IND,65,0,13.8,...,Est,Back,2474,64,NaN,NaN,NaN,NaN,48.2,No
2,157,Aaron Gordon,gordoaa01,SF,NaN,21,ORL,80,72,28.7,...,Est,Front,22774,29,NaN,NaN,NaN,NaN,40.0,No
3,352,Adreian Payne,paynead01,PF,NaN,25,MIN,18,0,7.5,...,West,Front,861,120,1.0,52.0,NaN,NaN,75.5,No
4,10,Al-Farouq Aminu,aminual01,PF,NaN,26,POR,61,25,29.1,...,West,Front,4971,69,7.0,23.0,NaN,NaN,42.8,No

In [ ]:
data.shape

(1408, 45)

In [ ]:
data.dtypes

Rk              int64
Player.x       object
Player_ID      object
Pos1           object
Pos2           object
Age             int64
Tm             object
G               int64
GS              int64
MP            float64
FG            float64
FGA           float64
FG.           float64
X3P           float64
X3PA          float64
X3P.          float64
X2P           float64
X2PA          float64
X2P.          float64
eFG.          float64
FT            float64
FTA           float64
FT.           float64
ORB           float64
DRB           float64
TRB           float64
AST           float64
STL           float64
BLK           float64
TOV           float64
PF            float64
PTS           float64
Salary        float64
mean_views    float64
Season         object
Conference     object
Role           object
Fvot            int64
FRank           int64
Pvot          float64
PRank         float64
Mvot          float64
MRank         float64
Score         float64
Play           object
dtype: object

In [ ]:
data.isnull().sum()

Rk               0
Player.x         0
Player_ID        0
Pos1             0
Pos2          1396
Age              0
Tm               0
G                0
GS               0
MP               0
FG               0
FGA              0
FG.              4
X3P              0
X3PA             0
X3P.            99
X2P              0
X2PA             0
X2P.            15
eFG.             4
FT               0
FTA              0
FT.             47
ORB              0
DRB              0
TRB              0
AST              0
STL              0
BLK              0
TOV              0
PF               0
PTS              0
Salary          62
mean_views     138
Season           0
Conference       0
Role             0
Fvot             0
FRank            0
Pvot           159
PRank          159
Mvot           404
MRank          404
Score            0
Play             0
dtype: int64

In [ ]:
data['Pos2'] = data['Pos2'].fillna('None')

In [ ]:
data.isnull().sum()

Rk              0
Player.x        0
Player_ID       0
Pos1            0
Pos2            0
Age             0
Tm              0
G               0
GS              0
MP              0
FG              0
FGA             0
FG.             4
X3P             0
X3PA            0
X3P.           99
X2P             0
X2PA            0
X2P.           15
eFG.            4
FT              0
FTA             0
FT.            47
ORB             0
DRB             0
TRB             0
AST             0
STL             0
BLK             0
TOV             0
PF              0
PTS             0
Salary         62
mean_views    138
Season          0
Conference      0
Role            0
Fvot            0
FRank           0
Pvot          159
PRank         159
Mvot          404
MRank         404
Score           0
Play            0
dtype: int64

In [ ]:
data['Salary'].median()

3384298.5

In [ ]:
data['Salary'] = data['Salary'].fillna(data['Salary'].median())
#data['Salary'].fillna(data['Salary'].median(), inplace = True)

In [ ]:
data = data.fillna(0)

In [ ]:
data.isnull().sum()

Rk            0
Player.x      0
Player_ID     0
Pos1          0
Pos2          0
Age           0
Tm            0
G             0
GS            0
MP            0
FG            0
FGA           0
FG.           0
X3P           0
X3PA          0
X3P.          0
X2P           0
X2PA          0
X2P.          0
eFG.          0
FT            0
FTA           0
FT.           0
ORB           0
DRB           0
TRB           0
AST           0
STL           0
BLK           0
TOV           0
PF            0
PTS           0
Salary        0
mean_views    0
Season        0
Conference    0
Role          0
Fvot          0
FRank         0
Pvot          0
PRank         0
Mvot          0
MRank         0
Score         0
Play          0
dtype: int64

In [ ]:
#check for the duplicates
data.duplicated().sum()

0

In [ ]:
data.drop_duplicates(inplace = True)

In [ ]:
data.head()

,Rk,Player.x,Player_ID,Pos1,Pos2,Age,Tm,G,GS,MP,...,Conference,Role,Fvot,FRank,Pvot,PRank,Mvot,MRank,Score,Play
0,170,A.J. Hammons,hammoaj01,C,None,24,DAL,22,0,7.4,...,West,Front,786,123,0.0,0.0,0.0,0.0,83.5,No
1,58,Aaron Brooks,brookaa01,PG,None,32,IND,65,0,13.8,...,Est,Back,2474,64,0.0,0.0,0.0,0.0,48.2,No
2,157,Aaron Gordon,gordoaa01,SF,None,21,ORL,80,72,28.7,...,Est,Front,22774,29,0.0,0.0,0.0,0.0,40.0,No
3,352,Adreian Payne,paynead01,PF,None,25,MIN,18,0,7.5,...,West,Front,861,120,1.0,52.0,0.0,0.0,75.5,No
4,10,Al-Farouq Aminu,aminual01,PF,None,26,POR,61,25,29.1,...,West,Front,4971,69,7.0,23.0,0.0,0.0,42.8,No

In [ ]:
data.drop(columns = ['Player.x', 'Player_ID'], inplace = True)

In [ ]:
obj_cols = data.select_dtypes('object').columns

In [ ]:
obj_cols

Index(['Pos1', 'Pos2', 'Tm', 'Season', 'Conference', 'Role', 'Play'], dtype='object')

In [ ]:
num_cols = data.select_dtypes('number').columns

In [ ]:
num_cols

Index(['Rk', 'Age', 'G', 'GS', 'MP', 'FG', 'FGA', 'FG.', 'X3P', 'X3PA', 'X3P.',
       'X2P', 'X2PA', 'X2P.', 'eFG.', 'FT', 'FTA', 'FT.', 'ORB', 'DRB', 'TRB',
       'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS', 'Salary', 'mean_views', 'Fvot',
       'FRank', 'Pvot', 'PRank', 'Mvot', 'MRank', 'Score'],
      dtype='object')

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
le = LabelEncoder()

In [ ]:
for col in obj_cols:
  data[col] = le.fit_transform(data[col])

In [ ]:
data['Play'].value_counts()

Play
0    1335
1      73
Name: count, dtype: int64

### **Machine Learning Process**

In [ ]:
X = data.drop(columns = 'Play')
y = data['Play']

In [ ]:
#Splitting the data into Training and Tes sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, stratify = y, random_state = 42)

#### Standardization of the data

- To be done after splitting the data always.
- Standaridization should be done only when you are using Linear Algorithms like Linear Regression, Logistic Regression, SVM etc. We don't have to do standaridization when using Tree Based Algorithms.

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

### **Apply Logistic Regression on the data**

In [ ]:
log_reg = LogisticRegression()
log_reg.fit(X_train_scaled, y_train)

LogisticRegression()

In [ ]:
y_pred = log_reg.predict(X_test_scaled)

In [ ]:
accuracy_score(y_test, y_pred)

0.975177304964539

In [ ]:
roc_auc_score(y_test, y_pred)

0.7981273408239701

In [ ]:
X.shape

(1408, 42)

### **Transform the data with PCA**

In [ ]:
from sklearn.decomposition import PCA

In [ ]:
pca = PCA(n_components = 0.9)

In [ ]:
X_train_pca = pca.fit_transform(X_train_scaled)
X_test_pca = pca.transform(X_test_scaled)

In [ ]:
X_train_pca.shape

(1126, 22)

In [ ]:
pd.DataFrame(X_train_pca)

,0,1,2,3,4,5,6,7,8,9,...,12,13,14,15,16,17,18,19,20,21
0,2.025099,2.813653,-0.794152,1.325493,-1.198556,-0.725060,-1.147976,1.366034,-0.386061,0.728520,...,-0.955882,0.353595,-0.722377,-0.002213,-0.837960,0.536865,-0.746995,0.312106,0.205621,-0.295054
1,1.072688,2.363635,0.486947,-0.443000,2.011819,1.218685,2.257109,1.445943,-0.346723,-0.337356,...,0.380438,-0.708538,0.711996,0.631999,0.482681,-0.582445,-1.339282,-1.629356,-0.499620,1.356827
2,15.416376,1.835152,9.978098,2.660534,6.910062,1.575976,-1.719525,1.054251,-0.647985,0.439230,...,1.202805,0.909677,-0.419857,-1.180338,1.190998,3.323544,0.779063,-0.486152,1.399088,-1.889863
3,-3.749860,-2.023922,0.890091,-2.621400,2.892572,1.225526,1.635200,1.339934,-0.242953,-0.269914,...,-0.993830,0.352835,-1.074673,-0.113813,0.037522,-0.270146,-0.629793,-0.291845,-0.267243,0.548556
4,2.762714,1.964859,-0.135180,0.988875,-1.031335,-0.323098,0.771864,3.128929,-0.850608,0.503215,...,0.773591,0.760613,0.813833,-0.640171,-0.373717,-1.448978,0.836024,0.060960,0.410896,-0.518860
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1121,-3.515270,0.168790,1.486070,1.131188,-0.338187,2.478841,1.554376,-0.343830,-0.109429,-0.372265,...,-0.160399,-0.079069,-0.060301,-0.190713,-0.466831,-0.395415,1.827842,-0.007978,-0.039175,-0.158131
1122,1.886794,2.243863,-0.876607,-0.014914,0.321664,-0.224116,0.371568,0.454492,0.458554,-1.858144,...,-0.051589,-0.848010,-0.042089,0.661080,0.729373,0.735935,0.018452,0.658105,-0.051329,0.222959
1123,-1.202440,0.481528,0.158046,0.658273,0.353037,-2.014807,1.758111,0.915570,-0.043936,-0.483261,...,-0.159960,0.502387,0.074386,-0.891890,-0.758965,0.278697,0.008054,0.493501,0.325493,0.196073
1124,3.060127,-5.067347,0.728127,-2.850854,-0.379353,0.906406,-1.839570,0.960320,0.090426,-0.477536,...,-0.296086,-0.920447,-0.437657,0.739979,-0.286634,0.336556,0.438750,0.985779,-0.885885,-0.516268
1125,-3.333024,-0.318945,-0.341725,1.556851,0.716659,1.527733,1.702673,-0.513877,-0.693901,1.016210,...,0.409903,1.350350,0.337955,-0.424339,0.276750,-0.006124,0.188807,0.103158,0.344647,-0.188064

### **Applying the Logistic Regression on the data which is transformed using PCA**

In [ ]:
log_reg2 = LogisticRegression()

log_reg2.fit(X_train_pca, y_train)

LogisticRegression()

In [ ]:
y_pred2 = log_reg2.predict(X_test_pca)

In [ ]:
roc_auc_score(y_test, y_pred2)

0.7666666666666666

### **Transforming the data with LDA**

In [ ]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

In [ ]:
lda = LinearDiscriminantAnalysis()

In [ ]:
X =